























.build/diecimila-55156a30/Servo/Servo.o : /home/jesse/code/arduino/arduino-1.0.5/libraries/Servo/Servo.cpp
	@echo Servo/Servo.cpp
	@mkdir -p .build/diecimila-55156a30/Servo
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/libraries/Servo/Servo.cpp
include .build/diecimila-55156a30/Servo/Servo.d



.build/diecimila-55156a30/Servo/libServo.a : .build/diecimila-55156a30/Servo/Servo.o
	@echo Linking libServo.a
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/diecimila-55156a30/arduino/wiring.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/wiring.c
	@echo arduino/wiring.c
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/wiring.c
include .build/diecimila-55156a30/arduino/wiring.d

.build/diecimila-55156a30/arduino/wiring_shift.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_shift.c
	@echo arduino/wiring_shift.c
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_shift.c
include .build/diecimila-55156a30/arduino/wiring_shift.d

.build/diecimila-55156a30/arduino/wiring_analog.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_analog.c
	@echo arduino/wiring_analog.c
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_analog.c
include .build/diecimila-55156a30/arduino/wiring_analog.d

.build/diecimila-55156a30/arduino/WInterrupts.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/WInterrupts.c
	@echo arduino/WInterrupts.c
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/WInterrupts.c
include .build/diecimila-55156a30/arduino/WInterrupts.d

.build/diecimila-55156a30/arduino/wiring_pulse.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo arduino/wiring_pulse.c
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/diecimila-55156a30/arduino/wiring_pulse.d

.build/diecimila-55156a30/arduino/wiring_digital.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_digital.c
	@echo arduino/wiring_digital.c
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/wiring_digital.c
include .build/diecimila-55156a30/arduino/wiring_digital.d

.build/diecimila-55156a30/arduino/avr-libc/realloc.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc/realloc.c
	@echo arduino/avr-libc/realloc.c
	@mkdir -p .build/diecimila-55156a30/arduino/avr-libc
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc/realloc.c
include .build/diecimila-55156a30/arduino/avr-libc/realloc.d

.build/diecimila-55156a30/arduino/avr-libc/malloc.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc/malloc.c
	@echo arduino/avr-libc/malloc.c
	@mkdir -p .build/diecimila-55156a30/arduino/avr-libc
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc/malloc.c
include .build/diecimila-55156a30/arduino/avr-libc/malloc.d






.build/diecimila-55156a30/arduino/HardwareSerial.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo arduino/HardwareSerial.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/diecimila-55156a30/arduino/HardwareSerial.d

.build/diecimila-55156a30/arduino/Tone.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/Tone.cpp
	@echo arduino/Tone.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/Tone.cpp
include .build/diecimila-55156a30/arduino/Tone.d

.build/diecimila-55156a30/arduino/Print.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/Print.cpp
	@echo arduino/Print.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/Print.cpp
include .build/diecimila-55156a30/arduino/Print.d

.build/diecimila-55156a30/arduino/WMath.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/WMath.cpp
	@echo arduino/WMath.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/WMath.cpp
include .build/diecimila-55156a30/arduino/WMath.d

.build/diecimila-55156a30/arduino/Stream.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/Stream.cpp
	@echo arduino/Stream.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/Stream.cpp
include .build/diecimila-55156a30/arduino/Stream.d

.build/diecimila-55156a30/arduino/IPAddress.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo arduino/IPAddress.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/diecimila-55156a30/arduino/IPAddress.d

.build/diecimila-55156a30/arduino/USBCore.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/USBCore.cpp
	@echo arduino/USBCore.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/USBCore.cpp
include .build/diecimila-55156a30/arduino/USBCore.d

.build/diecimila-55156a30/arduino/WString.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/WString.cpp
	@echo arduino/WString.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/WString.cpp
include .build/diecimila-55156a30/arduino/WString.d

.build/diecimila-55156a30/arduino/CDC.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/CDC.cpp
	@echo arduino/CDC.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/CDC.cpp
include .build/diecimila-55156a30/arduino/CDC.d

.build/diecimila-55156a30/arduino/new.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/new.cpp
	@echo arduino/new.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/new.cpp
include .build/diecimila-55156a30/arduino/new.d

.build/diecimila-55156a30/arduino/HID.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/HID.cpp
	@echo arduino/HID.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/HID.cpp
include .build/diecimila-55156a30/arduino/HID.d

.build/diecimila-55156a30/arduino/main.o : /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/main.cpp
	@echo arduino/main.cpp
	@mkdir -p .build/diecimila-55156a30/arduino
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/main.cpp
include .build/diecimila-55156a30/arduino/main.d



.build/diecimila-55156a30/arduino/libarduino.a : .build/diecimila-55156a30/arduino/wiring.o .build/diecimila-55156a30/arduino/wiring_shift.o .build/diecimila-55156a30/arduino/wiring_analog.o .build/diecimila-55156a30/arduino/WInterrupts.o .build/diecimila-55156a30/arduino/wiring_pulse.o .build/diecimila-55156a30/arduino/wiring_digital.o .build/diecimila-55156a30/arduino/avr-libc/realloc.o .build/diecimila-55156a30/arduino/avr-libc/malloc.o .build/diecimila-55156a30/arduino/HardwareSerial.o .build/diecimila-55156a30/arduino/Tone.o .build/diecimila-55156a30/arduino/Print.o .build/diecimila-55156a30/arduino/WMath.o .build/diecimila-55156a30/arduino/Stream.o .build/diecimila-55156a30/arduino/IPAddress.o .build/diecimila-55156a30/arduino/USBCore.o .build/diecimila-55156a30/arduino/WString.o .build/diecimila-55156a30/arduino/CDC.o .build/diecimila-55156a30/arduino/new.o .build/diecimila-55156a30/arduino/HID.o .build/diecimila-55156a30/arduino/main.o
	@echo Linking libarduino.a
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/diecimila-55156a30/src/ISR.o : src/ISR.c
	@echo src/ISR.c
	@mkdir -p .build/diecimila-55156a30/src
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc   -o $@ -c src/ISR.c
include .build/diecimila-55156a30/src/ISR.d









.build/diecimila-55156a30/src/Burner.o : .build/diecimila-55156a30/src/Burner.cpp
	@echo src/Burner.cpp
	@mkdir -p .build/diecimila-55156a30/src
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-g++ -mmcu=atmega168 -DF_CPU=16000000L -DARDUINO=105 -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/variants/standard -I/home/jesse/code/arduino/arduino-1.0.5/libraries/Servo -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino -I/home/jesse/code/arduino/arduino-1.0.5/hardware/arduino/cores/arduino/avr-libc -fno-exceptions -iquote src  -o $@ -c .build/diecimila-55156a30/src/Burner.cpp
include .build/diecimila-55156a30/src/Burner.d







.build/diecimila-55156a30/firmware.elf : .build/diecimila-55156a30/src/ISR.o .build/diecimila-55156a30/src/Burner.o .build/diecimila-55156a30/Servo/libServo.a .build/diecimila-55156a30/arduino/libarduino.a
	@echo Linking firmware.elf
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-gcc -mmcu=atmega168 -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/diecimila-55156a30/firmware.hex : .build/diecimila-55156a30/firmware.elf
	@echo Converting to firmware.hex
	@/home/jesse/code/arduino/arduino-1.0.5/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/diecimila-55156a30/src/dependencies.d .build/diecimila-55156a30/Servo/dependencies.d .build/diecimila-55156a30/arduino/dependencies.d

all : .build/diecimila-55156a30/firmware.hex
	@true

